double _boysFunction(const double );
vector<double> _calcRP(const double , const double , vector<double> const& , vector<double> const& );
double _calcSItg4idxElement(const double , const double , const double );
double _calcTElementWithS(const double , const double , const double );
double _calcVElementWithS(const double , const double , const double , const double );
double _calcKFactorElement(const double , const double , const double );
double _calcEItgElementWithKs(const double , const double , const double , const double , const double );
double _calcEItgElement(vector<vector<vector<vector<double>>>>& , vector<Basis> const& , const int , const int , const int , const int );
void initializeMat2idx(vector<vector<double>>& , const int );
void initializeMat4idx(vector<vector<vector<vector<double>>>>& , vector<Basis> const& );
void initializeEItg(vector<vector<vector<vector<double>>>>& , const int );
void calcDisMat(vector<vector<double>>& , vector<Basis> const& );
void calcSItg4idx(vector<vector<vector<vector<double>>>>& , vector<Basis> const& , vector<vector<double>> const& );
void calcSItg(vector<vector<double>>& , vector<vector<vector<vector<double>>>> const& , vector<Basis> const& );
void calcTItg(vector<vector<double>>& , vector<vector<vector<vector<double>>>> const& , vector<Basis> const& , vector<vector<double>> const& );
void calcVItg(vector<vector<double>>& , vector<vector<vector<vector<double>>>> const& , vector<Basis> const& , vector<Atom> const& );
void _calcKFactor(vector<vector<vector<vector<double>>>>& , vector<Basis> const& , vector<Atom> const& ,vector<vector<double>> const& );
void calcEItg(vector<vector<vector<vector<double>>>>& , vector<Basis> const& , vector<Atom> const& ,vector<vector<double>> const& );